# Generated by Django 3.0.8 on 2020-07-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topic',
        ),
        migrations.AddField(
            model_name='blog',
            name='field_tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
