# Generated by Django 3.0.8 on 2020-07-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=30)),
                ('query', models.TextField()),
                ('date_of_appointment', models.DateField(blank=True, null=True)),
                ('time_of_appointment', models.TimeField(blank=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PatientInfo.Locations')),
            ],
        ),
    ]
