# Generated by Django 3.0.8 on 2020-07-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
