# Generated by Django 3.0.8 on 2020-07-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_testimonials_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='work_address',
        ),
    ]
